### ISSUE TITLE
Migrate to gradle 8

### ISSUE THREAD

**Issue by ukinimod** [feature-creeps/observability-workshop#109]
As a developer I want gradle to be upgraded to version 8 in order to keep the code maintainable.

Info:
- gradle plugin [de.db.vz.msintplugin](https://github.com/dbsystel/microservice-integrationtest-gradle-plugin) is not compatible to gradle 8. Ask @xellsys about plugin. Idea: Deinstall plugin and switch to different solution.

**Comment by BlacCello** [comment]
Already handled with #132 
msintplugin was not used anyway, so removed.
