### ISSUE TITLE
Dry run on how to ssh from linux and windows

### ISSUE THREAD

**Issue by abangser** [feature-creeps/observability-workshop#2]
"in an ideal world you would not need ssh to explore the architecture. let's see how that works out."

pre-req:
- test out ssh just as myself
- generate a visualisation of the environment (grafana?)

Outcomes from this dry run are to:
- confirm ssh can work when docker-machine is brought up on a different computer
- get a feel for how someone new explores the app architecture given a GUI tool that provides info
- get a feel for how much ssh is needed given the right visualiser app

**Comment by xellsys** [comment]
Can we close this?
