### ISSUE TITLE
Access prometheus endpoints for domain specific services from web browser

### ISSUE THREAD

**Issue by abangser** [feature-creeps/observability-workshop#25]
On the targets page in prometheus we are able to see what services are scraped but they only display the magical internal DNS urls. Attendees being able to see what the endpoints look like could help them identify if a question can be answered.

possibly solution: write some nginx magic to redirect `http://<ip>:9876/<servicename>` would be able to redirect to the `http://imageflip:8080/actuator/prometheus` endpoint.

**Comment by xellsys** [comment]
You can use the reverse proxy for that:
http://<ip>/proxy/<servicename>/actuator/prometheus
eg: http://46.101.170.74/proxy/imageholder/actuator/prometheus
