### ISSUE TITLE
Imageorchestrator was functioning but no logs were received

### ISSUE THREAD

**Issue by xellsys** [feature-creeps/observability-workshop#60]
There was a state in which the imageorchestrator was functioning properly (via UI, image manipulation etc) and also shown as up and healthy by the prometheus scrape (services up dashboard in grafana), but at the same time no log or event was found in kibana. Other services were also functioning properly and logs/events were displayed in kibana just fine.

Idea: possibly the mapping of the event and/or logs index was denying documents from the imageorchestrator as it sent a field with an incompatible value, eg some alphabetical text in a number field.

**Comment by ukinimod** [comment]
Couldn't observe the issue.
